#ifndef __NMGLDEF_H__
#define __NMGLDEF_H__


#define NMGL_VERSION_ES_CL_1_0              GL_VERSION_ES_CL_1_0              
#define NMGL_VERSION_ES_CM_1_1              GL_VERSION_ES_CM_1_1              
#define NMGL_VERSION_ES_CL_1_1              GL_VERSION_ES_CL_1_1              
#define NMGL_DEPTH_BUFFER_BIT               GL_DEPTH_BUFFER_BIT               
#define NMGL_STENCIL_BUFFER_BIT             GL_STENCIL_BUFFER_BIT             
#define NMGL_COLOR_BUFFER_BIT               GL_COLOR_BUFFER_BIT               
#define NMGL_FALSE                          GL_FALSE                          
#define NMGL_TRUE                           GL_TRUE                           
#define NMGL_POINTS                         GL_POINTS                         
#define NMGL_LINES                          GL_LINES                          
#define NMGL_LINE_LOOP                      GL_LINE_LOOP                      
#define NMGL_LINE_STRIP                     GL_LINE_STRIP                     
#define NMGL_TRIANGLES                      GL_TRIANGLES                      
#define NMGL_TRIANGLE_STRIP                 GL_TRIANGLE_STRIP                 
#define NMGL_TRIANGLE_FAN                   GL_TRIANGLE_FAN                   
#define NMGL_NEVER                          GL_NEVER                          
#define NMGL_LESS                           GL_LESS                           
#define NMGL_EQUAL                          GL_EQUAL                          
#define NMGL_LEQUAL                         GL_LEQUAL                         
#define NMGL_GREATER                        GL_GREATER                        
#define NMGL_NOTEQUAL                       GL_NOTEQUAL                       
#define NMGL_GEQUAL                         GL_GEQUAL                         
#define NMGL_ALWAYS                         GL_ALWAYS                         
#define NMGL_ZERO                           GL_ZERO                           
#define NMGL_ONE                            GL_ONE                            
#define NMGL_SRC_COLOR                      GL_SRC_COLOR                      
#define NMGL_ONE_MINUS_SRC_COLOR            GL_ONE_MINUS_SRC_COLOR            
#define NMGL_SRC_ALPHA                      GL_SRC_ALPHA                      
#define NMGL_ONE_MINUS_SRC_ALPHA            GL_ONE_MINUS_SRC_ALPHA            
#define NMGL_DST_ALPHA                      GL_DST_ALPHA                      
#define NMGL_ONE_MINUS_DST_ALPHA            GL_ONE_MINUS_DST_ALPHA            
#define NMGL_DST_COLOR                      GL_DST_COLOR                      
#define NMGL_ONE_MINUS_DST_COLOR            GL_ONE_MINUS_DST_COLOR            
#define NMGL_SRC_ALPHA_SATURATE             GL_SRC_ALPHA_SATURATE             
#define NMGL_CLIP_PLANE0                    GL_CLIP_PLANE0                    
#define NMGL_CLIP_PLANE1                    GL_CLIP_PLANE1                    
#define NMGL_CLIP_PLANE2                    GL_CLIP_PLANE2                    
#define NMGL_CLIP_PLANE3                    GL_CLIP_PLANE3                    
#define NMGL_CLIP_PLANE4                    GL_CLIP_PLANE4                    
#define NMGL_CLIP_PLANE5                    GL_CLIP_PLANE5                    
#define NMGL_FRONT                          GL_FRONT                          
#define NMGL_BACK                           GL_BACK                           
#define NMGL_FRONT_AND_BACK                 GL_FRONT_AND_BACK                 
#define NMGL_FOG                            GL_FOG                            
#define NMGL_LIGHTING                       GL_LIGHTING                       
#define NMGL_TEXTURE_2D                     GL_TEXTURE_2D                     
#define NMGL_CULL_FACE                      GL_CULL_FACE                      
#define NMGL_ALPHA_TEST                     GL_ALPHA_TEST                     
#define NMGL_BLEND                          GL_BLEND                          
#define NMGL_COLOR_LOGIC_OP                 GL_COLOR_LOGIC_OP                 
#define NMGL_DITHER                         GL_DITHER                         
#define NMGL_STENCIL_TEST                   GL_STENCIL_TEST                   
#define NMGL_DEPTH_TEST                     GL_DEPTH_TEST                     
#define NMGL_POINT_SMOOTH                   GL_POINT_SMOOTH                   
#define NMGL_LINE_SMOOTH                    GL_LINE_SMOOTH                    
#define NMGL_SCISSOR_TEST                   GL_SCISSOR_TEST                   
#define NMGL_COLOR_MATERIAL                 GL_COLOR_MATERIAL                 
#define NMGL_NORMALIZE                      GL_NORMALIZE                      
#define NMGL_RESCALE_NORMAL                 GL_RESCALE_NORMAL                 
#define NMGL_VERTEX_ARRAY                   GL_VERTEX_ARRAY                   
#define NMGL_NORMAL_ARRAY                   GL_NORMAL_ARRAY                   
#define NMGL_COLOR_ARRAY                    GL_COLOR_ARRAY                    
#define NMGL_TEXTURE_COORD_ARRAY            GL_TEXTURE_COORD_ARRAY            
#define NMGL_MULTISAMPLE                    GL_MULTISAMPLE                    
#define NMGL_SAMPLE_ALPHA_TO_COVERAGE       GL_SAMPLE_ALPHA_TO_COVERAGE       
#define NMGL_SAMPLE_ALPHA_TO_ONE            GL_SAMPLE_ALPHA_TO_ONE            
#define NMGL_SAMPLE_COVERAGE                GL_SAMPLE_COVERAGE                
#define NMGL_NO_ERROR                       GL_NO_ERROR                       
#define NMGL_INVALID_ENUM                   GL_INVALID_ENUM                   
#define NMGL_INVALID_VALUE                  GL_INVALID_VALUE                  
#define NMGL_INVALID_OPERATION              GL_INVALID_OPERATION              
#define NMGL_STACK_OVERFLOW                 GL_STACK_OVERFLOW                 
#define NMGL_STACK_UNDERFLOW                GL_STACK_UNDERFLOW                
#define NMGL_OUT_OF_MEMORY                  GL_OUT_OF_MEMORY                  
#define NMGL_EXP                            GL_EXP                            
#define NMGL_EXP2                           GL_EXP2                           
#define NMGL_FOG_DENSITY                    GL_FOG_DENSITY                    
#define NMGL_FOG_START                      GL_FOG_START                      
#define NMGL_FOG_END                        GL_FOG_END                        
#define NMGL_FOG_MODE                       GL_FOG_MODE                       
#define NMGL_FOG_COLOR                      GL_FOG_COLOR                      
#define NMGL_CW                             GL_CW                             
#define NMGL_CCW                            GL_CCW                            
#define NMGL_CURRENT_COLOR                  GL_CURRENT_COLOR                  
#define NMGL_CURRENT_NORMAL                 GL_CURRENT_NORMAL                 
#define NMGL_CURRENT_TEXTURE_COORDS         GL_CURRENT_TEXTURE_COORDS         
#define NMGL_POINT_SIZE                     GL_POINT_SIZE                     
#define NMGL_POINT_SIZE_MIN                 GL_POINT_SIZE_MIN                 
#define NMGL_POINT_SIZE_MAX                 GL_POINT_SIZE_MAX                 
#define NMGL_POINT_FADE_THRESHOLD_SIZE      GL_POINT_FADE_THRESHOLD_SIZE      
#define NMGL_POINT_DISTANCE_ATTENUATION     GL_POINT_DISTANCE_ATTENUATION     
#define NMGL_SMOOTH_POINT_SIZE_RANGE        GL_SMOOTH_POINT_SIZE_RANGE        
#define NMGL_LINE_WIDTH                     GL_LINE_WIDTH                     
#define NMGL_SMOOTH_LINE_WIDTH_RANGE        GL_SMOOTH_LINE_WIDTH_RANGE        
#define NMGL_ALIASED_POINT_SIZE_RANGE       GL_ALIASED_POINT_SIZE_RANGE       
#define NMGL_ALIASED_LINE_WIDTH_RANGE       GL_ALIASED_LINE_WIDTH_RANGE       
#define NMGL_CULL_FACE_MODE                 GL_CULL_FACE_MODE                 
#define NMGL_FRONT_FACE                     GL_FRONT_FACE                     
#define NMGL_SHADE_MODEL                    GL_SHADE_MODEL                    
#define NMGL_DEPTH_RANGE                    GL_DEPTH_RANGE                    
#define NMGL_DEPTH_WRITEMASK                GL_DEPTH_WRITEMASK                
#define NMGL_DEPTH_CLEAR_VALUE              GL_DEPTH_CLEAR_VALUE              
#define NMGL_DEPTH_FUNC                     GL_DEPTH_FUNC                     
#define NMGL_STENCIL_CLEAR_VALUE            GL_STENCIL_CLEAR_VALUE            
#define NMGL_STENCIL_FUNC                   GL_STENCIL_FUNC                   
#define NMGL_STENCIL_VALUE_MASK             GL_STENCIL_VALUE_MASK             
#define NMGL_STENCIL_FAIL                   GL_STENCIL_FAIL                   
#define NMGL_STENCIL_PASS_DEPTH_FAIL        GL_STENCIL_PASS_DEPTH_FAIL        
#define NMGL_STENCIL_PASS_DEPTH_PASS        GL_STENCIL_PASS_DEPTH_PASS        
#define NMGL_STENCIL_REF                    GL_STENCIL_REF                    
#define NMGL_STENCIL_WRITEMASK              GL_STENCIL_WRITEMASK              
#define NMGL_MATRIX_MODE                    GL_MATRIX_MODE                    
#define NMGL_VIEWPORT                       GL_VIEWPORT                       
#define NMGL_MODELVIEW_STACK_DEPTH          GL_MODELVIEW_STACK_DEPTH          
#define NMGL_PROJECTION_STACK_DEPTH         GL_PROJECTION_STACK_DEPTH         
#define NMGL_TEXTURE_STACK_DEPTH            GL_TEXTURE_STACK_DEPTH            
#define NMGL_MODELVIEW_MATRIX               GL_MODELVIEW_MATRIX               
#define NMGL_PROJECTION_MATRIX              GL_PROJECTION_MATRIX              
#define NMGL_TEXTURE_MATRIX                 GL_TEXTURE_MATRIX                 
#define NMGL_ALPHA_TEST_FUNC                GL_ALPHA_TEST_FUNC                
#define NMGL_ALPHA_TEST_REF                 GL_ALPHA_TEST_REF                 
#define NMGL_BLEND_DST                      GL_BLEND_DST                      
#define NMGL_BLEND_SRC                      GL_BLEND_SRC                      
#define NMGL_LOGIC_OP_MODE                  GL_LOGIC_OP_MODE                  
#define NMGL_SCISSOR_BOX                    GL_SCISSOR_BOX                    
#define NMGL_COLOR_CLEAR_VALUE              GL_COLOR_CLEAR_VALUE              
#define NMGL_COLOR_WRITEMASK                GL_COLOR_WRITEMASK                
#define NMGL_MAX_LIGHTS                     GL_MAX_LIGHTS                     
#define NMGL_MAX_CLIP_PLANES                GL_MAX_CLIP_PLANES                
#define NMGL_MAX_TEXTURE_SIZE               GL_MAX_TEXTURE_SIZE               
#define NMGL_MAX_MODELVIEW_STACK_DEPTH      GL_MAX_MODELVIEW_STACK_DEPTH      
#define NMGL_MAX_PROJECTION_STACK_DEPTH     GL_MAX_PROJECTION_STACK_DEPTH     
#define NMGL_MAX_TEXTURE_STACK_DEPTH        GL_MAX_TEXTURE_STACK_DEPTH        
#define NMGL_MAX_VIEWPORT_DIMS              GL_MAX_VIEWPORT_DIMS              
#define NMGL_MAX_TEXTURE_UNITS              GL_MAX_TEXTURE_UNITS              
#define NMGL_SUBPIXEL_BITS                  GL_SUBPIXEL_BITS                  
#define NMGL_RED_BITS                       GL_RED_BITS                       
#define NMGL_GREEN_BITS                     GL_GREEN_BITS                     
#define NMGL_BLUE_BITS                      GL_BLUE_BITS                      
#define NMGL_ALPHA_BITS                     GL_ALPHA_BITS                     
#define NMGL_DEPTH_BITS                     GL_DEPTH_BITS                     
#define NMGL_STENCIL_BITS                   GL_STENCIL_BITS                   
#define NMGL_POLYGON_OFFSET_UNITS           GL_POLYGON_OFFSET_UNITS           
#define NMGL_POLYGON_OFFSET_FILL            GL_POLYGON_OFFSET_FILL            
#define NMGL_POLYGON_OFFSET_FACTOR          GL_POLYGON_OFFSET_FACTOR          
#define NMGL_TEXTURE_BINDING_2D             GL_TEXTURE_BINDING_2D             
#define NMGL_VERTEX_ARRAY_SIZE              GL_VERTEX_ARRAY_SIZE              
#define NMGL_VERTEX_ARRAY_TYPE              GL_VERTEX_ARRAY_TYPE              
#define NMGL_VERTEX_ARRAY_STRIDE            GL_VERTEX_ARRAY_STRIDE            
#define NMGL_NORMAL_ARRAY_TYPE              GL_NORMAL_ARRAY_TYPE              
#define NMGL_NORMAL_ARRAY_STRIDE            GL_NORMAL_ARRAY_STRIDE            
#define NMGL_COLOR_ARRAY_SIZE               GL_COLOR_ARRAY_SIZE               
#define NMGL_COLOR_ARRAY_TYPE               GL_COLOR_ARRAY_TYPE               
#define NMGL_COLOR_ARRAY_STRIDE             GL_COLOR_ARRAY_STRIDE             
#define NMGL_TEXTURE_COORD_ARRAY_SIZE       GL_TEXTURE_COORD_ARRAY_SIZE       
#define NMGL_TEXTURE_COORD_ARRAY_TYPE       GL_TEXTURE_COORD_ARRAY_TYPE       
#define NMGL_TEXTURE_COORD_ARRAY_STRIDE     GL_TEXTURE_COORD_ARRAY_STRIDE     
#define NMGL_VERTEX_ARRAY_POINTER           GL_VERTEX_ARRAY_POINTER           
#define NMGL_NORMAL_ARRAY_POINTER           GL_NORMAL_ARRAY_POINTER           
#define NMGL_COLOR_ARRAY_POINTER            GL_COLOR_ARRAY_POINTER            
#define NMGL_TEXTURE_COORD_ARRAY_POINTER    GL_TEXTURE_COORD_ARRAY_POINTER    
#define NMGL_SAMPLE_BUFFERS                 GL_SAMPLE_BUFFERS                 
#define NMGL_SAMPLES                        GL_SAMPLES                        
#define NMGL_SAMPLE_COVERAGE_VALUE          GL_SAMPLE_COVERAGE_VALUE          
#define NMGL_SAMPLE_COVERAGE_INVERT         GL_SAMPLE_COVERAGE_INVERT         
#define NMGL_NUM_COMPRESSED_TEXTURE_FORMATS GL_NUM_COMPRESSED_TEXTURE_FORMATS 
#define NMGL_COMPRESSED_TEXTURE_FORMATS     GL_COMPRESSED_TEXTURE_FORMATS     
#define NMGL_DONT_CARE                      GL_DONT_CARE                      
#define NMGL_FASTEST                        GL_FASTEST                        
#define NMGL_NICEST                         GL_NICEST                         
#define NMGL_PERSPECTIVE_CORRECTION_HINT    GL_PERSPECTIVE_CORRECTION_HINT    
#define NMGL_POINT_SMOOTH_HINT              GL_POINT_SMOOTH_HINT              
#define NMGL_LINE_SMOOTH_HINT               GL_LINE_SMOOTH_HINT               
#define NMGL_FOG_HINT                       GL_FOG_HINT                       
#define NMGL_GENERATE_MIPMAP_HINT           GL_GENERATE_MIPMAP_HINT           
#define NMGL_LIGHT_MODEL_AMBIENT            GL_LIGHT_MODEL_AMBIENT            
#define NMGL_LIGHT_MODEL_TWO_SIDE           GL_LIGHT_MODEL_TWO_SIDE           
#define NMGL_AMBIENT                        GL_AMBIENT                        
#define NMGL_DIFFUSE                        GL_DIFFUSE                        
#define NMGL_SPECULAR                       GL_SPECULAR                       
#define NMGL_POSITION                       GL_POSITION                       
#define NMGL_SPOT_DIRECTION                 GL_SPOT_DIRECTION                 
#define NMGL_SPOT_EXPONENT                  GL_SPOT_EXPONENT                  
#define NMGL_SPOT_CUTOFF                    GL_SPOT_CUTOFF                    
#define NMGL_CONSTANT_ATTENUATION           GL_CONSTANT_ATTENUATION           
#define NMGL_LINEAR_ATTENUATION             GL_LINEAR_ATTENUATION             
#define NMGL_QUADRATIC_ATTENUATION          GL_QUADRATIC_ATTENUATION          
#define NMGL_BYTE                           GL_BYTE                           
#define NMGL_UNSIGNED_BYTE                  GL_UNSIGNED_BYTE                  
#define NMGL_SHORT                          GL_SHORT                          
#define NMGL_UNSIGNED_SHORT                 GL_UNSIGNED_SHORT                 
#define NMGL_FLOAT                          GL_FLOAT                          
#define NMGL_FIXED                          GL_FIXED                          
#define NMGL_CLEAR                          GL_CLEAR                          
#define NMGL_AND                            GL_AND                            
#define NMGL_AND_REVERSE                    GL_AND_REVERSE                    
#define NMGL_COPY                           GL_COPY                           
#define NMGL_AND_INVERTED                   GL_AND_INVERTED                   
#define NMGL_NOOP                           GL_NOOP                           
#define NMGL_XOR                            GL_XOR                            
#define NMGL_OR                             GL_OR                             
#define NMGL_NOR                            GL_NOR                            
#define NMGL_EQUIV                          GL_EQUIV                          
#define NMGL_INVERT                         GL_INVERT                         
#define NMGL_OR_REVERSE                     GL_OR_REVERSE                     
#define NMGL_COPY_INVERTED                  GL_COPY_INVERTED                  
#define NMGL_OR_INVERTED                    GL_OR_INVERTED                    
#define NMGL_NAND                           GL_NAND                           
#define NMGL_SET                            GL_SET                            
#define NMGL_EMISSION                       GL_EMISSION                       
#define NMGL_SHININESS                      GL_SHININESS                      
#define NMGL_AMBIENT_AND_DIFFUSE            GL_AMBIENT_AND_DIFFUSE            
#define NMGL_MODELVIEW                      GL_MODELVIEW                      
#define NMGL_PROJECTION                     GL_PROJECTION                     
#define NMGL_TEXTURE                        GL_TEXTURE                        
#define NMGL_ALPHA                          GL_ALPHA                          
#define NMGL_RGB                            GL_RGB                            
#define NMGL_RGBA                           GL_RGBA                           
#define NMGL_LUMINANCE                      GL_LUMINANCE                      
#define NMGL_LUMINANCE_ALPHA                GL_LUMINANCE_ALPHA                
#define NMGL_UNPACK_ALIGNMENT               GL_UNPACK_ALIGNMENT               
#define NMGL_PACK_ALIGNMENT                 GL_PACK_ALIGNMENT                 
#define NMGL_UNSIGNED_SHORT_4_4_4_4         GL_UNSIGNED_SHORT_4_4_4_4         
#define NMGL_UNSIGNED_SHORT_5_5_5_1         GL_UNSIGNED_SHORT_5_5_5_1         
#define NMGL_UNSIGNED_SHORT_5_6_5           GL_UNSIGNED_SHORT_5_6_5           
#define NMGL_FLAT                           GL_FLAT                           
#define NMGL_SMOOTH                         GL_SMOOTH                         
#define NMGL_KEEP                           GL_KEEP                           
#define NMGL_REPLACE                        GL_REPLACE                        
#define NMGL_INCR                           GL_INCR                           
#define NMGL_DECR                           GL_DECR                           
#define NMGL_VENDOR                         GL_VENDOR                         
#define NMGL_RENDERER                       GL_RENDERER                       
#define NMGL_VERSION                        GL_VERSION                        
#define NMGL_EXTENSIONS                     GL_EXTENSIONS                     
#define NMGL_MODULATE                       GL_MODULATE                       
#define NMGL_DECAL                          GL_DECAL                          
#define NMGL_ADD                            GL_ADD                            
#define NMGL_TEXTURE_ENV_MODE               GL_TEXTURE_ENV_MODE               
#define NMGL_TEXTURE_ENV_COLOR              GL_TEXTURE_ENV_COLOR              
#define NMGL_TEXTURE_ENV                    GL_TEXTURE_ENV                    
#define NMGL_NEAREST                        GL_NEAREST                        
#define NMGL_LINEAR                         GL_LINEAR                         
#define NMGL_NEAREST_MIPMAP_NEAREST         GL_NEAREST_MIPMAP_NEAREST         
#define NMGL_LINEAR_MIPMAP_NEAREST          GL_LINEAR_MIPMAP_NEAREST          
#define NMGL_NEAREST_MIPMAP_LINEAR          GL_NEAREST_MIPMAP_LINEAR          
#define NMGL_LINEAR_MIPMAP_LINEAR           GL_LINEAR_MIPMAP_LINEAR           
#define NMGL_TEXTURE_MAG_FILTER             GL_TEXTURE_MAG_FILTER             
#define NMGL_TEXTURE_MIN_FILTER             GL_TEXTURE_MIN_FILTER             
#define NMGL_TEXTURE_WRAP_S                 GL_TEXTURE_WRAP_S                 
#define NMGL_TEXTURE_WRAP_T                 GL_TEXTURE_WRAP_T                 
#define NMGL_GENERATE_MIPMAP                GL_GENERATE_MIPMAP                
#define NMGL_TEXTURE0                       GL_TEXTURE0                       
#define NMGL_TEXTURE1                       GL_TEXTURE1                       
#define NMGL_TEXTURE2                       GL_TEXTURE2                       
#define NMGL_TEXTURE3                       GL_TEXTURE3                       
#define NMGL_TEXTURE4                       GL_TEXTURE4                       
#define NMGL_TEXTURE5                       GL_TEXTURE5                       
#define NMGL_TEXTURE6                       GL_TEXTURE6                       
#define NMGL_TEXTURE7                       GL_TEXTURE7                       
#define NMGL_TEXTURE8                       GL_TEXTURE8                       
#define NMGL_TEXTURE9                       GL_TEXTURE9                       
#define NMGL_TEXTURE10                      GL_TEXTURE10                      
#define NMGL_TEXTURE11                      GL_TEXTURE11                      
#define NMGL_TEXTURE12                      GL_TEXTURE12                      
#define NMGL_TEXTURE13                      GL_TEXTURE13                      
#define NMGL_TEXTURE14                      GL_TEXTURE14                      
#define NMGL_TEXTURE15                      GL_TEXTURE15                      
#define NMGL_TEXTURE16                      GL_TEXTURE16                      
#define NMGL_TEXTURE17                      GL_TEXTURE17                      
#define NMGL_TEXTURE18                      GL_TEXTURE18                      
#define NMGL_TEXTURE19                      GL_TEXTURE19                      
#define NMGL_TEXTURE20                      GL_TEXTURE20                      
#define NMGL_TEXTURE21                      GL_TEXTURE21                      
#define NMGL_TEXTURE22                      GL_TEXTURE22                      
#define NMGL_TEXTURE23                      GL_TEXTURE23                      
#define NMGL_TEXTURE24                      GL_TEXTURE24                      
#define NMGL_TEXTURE25                      GL_TEXTURE25                      
#define NMGL_TEXTURE26                      GL_TEXTURE26                      
#define NMGL_TEXTURE27                      GL_TEXTURE27                      
#define NMGL_TEXTURE28                      GL_TEXTURE28                      
#define NMGL_TEXTURE29                      GL_TEXTURE29                      
#define NMGL_TEXTURE30                      GL_TEXTURE30                      
#define NMGL_TEXTURE31                      GL_TEXTURE31                      
#define NMGL_ACTIVE_TEXTURE                 GL_ACTIVE_TEXTURE                 
#define NMGL_CLIENT_ACTIVE_TEXTURE          GL_CLIENT_ACTIVE_TEXTURE          
#define NMGL_REPEAT                         GL_REPEAT                         
#define NMGL_CLAMP_TO_EDGE                  GL_CLAMP_TO_EDGE                  
#define NMGL_LIGHT0                         GL_LIGHT0                         
#define NMGL_LIGHT1                         GL_LIGHT1                         
#define NMGL_LIGHT2                         GL_LIGHT2                         
#define NMGL_LIGHT3                         GL_LIGHT3                         
#define NMGL_LIGHT4                         GL_LIGHT4                         
#define NMGL_LIGHT5                         GL_LIGHT5                         
#define NMGL_LIGHT6                         GL_LIGHT6                         
#define NMGL_LIGHT7                         GL_LIGHT7                         
#define NMGL_ARRAY_BUFFER                   GL_ARRAY_BUFFER                   
#define NMGL_ELEMENT_ARRAY_BUFFER           GL_ELEMENT_ARRAY_BUFFER           
#define NMGL_ARRAY_BUFFER_BINDING           GL_ARRAY_BUFFER_BINDING           
#define NMGL_ELEMENT_ARRAY_BUFFER_BINDING   GL_ELEMENT_ARRAY_BUFFER_BINDING   
#define NMGL_VERTEX_ARRAY_BUFFER_BINDING    GL_VERTEX_ARRAY_BUFFER_BINDING    
#define NMGL_NORMAL_ARRAY_BUFFER_BINDING    GL_NORMAL_ARRAY_BUFFER_BINDING    
#define NMGL_COLOR_ARRAY_BUFFER_BINDING     GL_COLOR_ARRAY_BUFFER_BINDING     
#define NMGL_TEXTURE_COORD_ARRAY_BUFFER_BIND GL_TEXTURE_COORD_ARRAY_BUFFER_BIND
#define NMGL_STATIC_DRAW                    GL_STATIC_DRAW                    
#define NMGL_DYNAMIC_DRAW                   GL_DYNAMIC_DRAW                   
#define NMGL_BUFFER_SIZE                    GL_BUFFER_SIZE                    
#define NMGL_BUFFER_USAGE                   GL_BUFFER_USAGE                   
#define NMGL_SUBTRACT                       GL_SUBTRACT                       
#define NMGL_COMBINE                        GL_COMBINE                        
#define NMGL_COMBINE_RGB                    GL_COMBINE_RGB                    
#define NMGL_COMBINE_ALPHA                  GL_COMBINE_ALPHA                  
#define NMGL_RGB_SCALE                      GL_RGB_SCALE                      
#define NMGL_ADD_SIGNED                     GL_ADD_SIGNED                     
#define NMGL_INTERPOLATE                    GL_INTERPOLATE                    
#define NMGL_CONSTANT                       GL_CONSTANT                       
#define NMGL_PRIMARY_COLOR                  GL_PRIMARY_COLOR                  
#define NMGL_PREVIOUS                       GL_PREVIOUS                       
#define NMGL_OPERAND0_RGB                   GL_OPERAND0_RGB                   
#define NMGL_OPERAND1_RGB                   GL_OPERAND1_RGB                   
#define NMGL_OPERAND2_RGB                   GL_OPERAND2_RGB                   
#define NMGL_OPERAND0_ALPHA                 GL_OPERAND0_ALPHA                 
#define NMGL_OPERAND1_ALPHA                 GL_OPERAND1_ALPHA                 
#define NMGL_OPERAND2_ALPHA                 GL_OPERAND2_ALPHA                 
#define NMGL_ALPHA_SCALE                    GL_ALPHA_SCALE                    
#define NMGL_SRC0_RGB                       GL_SRC0_RGB                       
#define NMGL_SRC1_RGB                       GL_SRC1_RGB                       
#define NMGL_SRC2_RGB                       GL_SRC2_RGB                       
#define NMGL_SRC0_ALPHA                     GL_SRC0_ALPHA                     
#define NMGL_SRC1_ALPHA                     GL_SRC1_ALPHA                     
#define NMGL_SRC2_ALPHA                     GL_SRC2_ALPHA                     
#define NMGL_DOT3_RGB                       GL_DOT3_RGB                       
#define NMGL_DOT3_RGBA                      GL_DOT3_RGBA                      
	
#endif
