#ifndef NMGL_TEX_TESTS_CONFIG_H_
#define NMGL_TEX_TESTS_CONFIG_H_
/*
#define TEST_NMGL_ACTIVE_TEXTURE
#define TEST_NMGL_CLIENT_ACTIVE_TEXTURE
#define TEST_NMGL_MULTI_TEX_COORD_2F
#define TEST_NMGL_MULTI_TEX_COORD_2FV
#define TEST_NMGL_TEX_ENV_FV
#define TEST_NMGL_GET_TEX_ENV_FV
#define TEST_NMGL_GET_TEX_ENV_IV
*/
/*
#define TESTNMGL_GET_TEX_PARAMETER_IV
#define TEST_NMGL_TEX_ENV_I
*/
#define TEST_NMGL_GEN_TEXTURES 
#define TEST_NMGL_BIND_TEXTURE
#define TEST_NMGL_TEX_IMAGE_2D
#define TEST_NMGL_TEX_SUB_IMAGE_2D

//#define TEST_NMGL_TEX_PARAMETER_I
//#define TEST_NMGL_TEX_COORD_POINTER

#endif /* NMGL_TEX_TESTS_CONFIG_H_ */
