#include "scenarios.h"

SECTION(".test_data") Scenario scenarios[48] = { 
	{"1", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_NEAREST,					GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}}, 
	{"2", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_NEAREST,					GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"3", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_LINEAR,					GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"4", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_LINEAR,					GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"5", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_NEAREST_MIPMAP_NEAREST,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"6", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_NEAREST_MIPMAP_NEAREST,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"7", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_NEAREST_MIPMAP_LINEAR,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"8", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_NEAREST_MIPMAP_LINEAR,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"9", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_LINEAR_MIPMAP_NEAREST,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"10", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_LINEAR_MIPMAP_NEAREST,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"11", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_LINEAR_MIPMAP_LINEAR,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"12", 	GL_CLAMP_TO_EDGE,	GL_CLAMP_TO_EDGE,	GL_LINEAR_MIPMAP_LINEAR,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"13", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_NEAREST,					GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"14", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_NEAREST,					GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"15", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_LINEAR,					GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"16", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_LINEAR,					GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"17", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_NEAREST_MIPMAP_NEAREST,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"18", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_NEAREST_MIPMAP_NEAREST,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"19", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_NEAREST_MIPMAP_LINEAR,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"20", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_NEAREST_MIPMAP_LINEAR,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"21", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_LINEAR_MIPMAP_NEAREST,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"22", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_LINEAR_MIPMAP_NEAREST,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"23", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_LINEAR_MIPMAP_LINEAR,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"24", 	GL_CLAMP_TO_EDGE,	GL_REPEAT,			GL_LINEAR_MIPMAP_LINEAR,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"25", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_NEAREST,					GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"26", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_NEAREST,					GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"27", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_LINEAR,					GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"28", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_LINEAR,					GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"29", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_NEAREST_MIPMAP_NEAREST,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"30", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_NEAREST_MIPMAP_NEAREST,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"31", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_NEAREST_MIPMAP_LINEAR,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"32", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_NEAREST_MIPMAP_LINEAR,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"33", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_LINEAR_MIPMAP_NEAREST,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"34", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_LINEAR_MIPMAP_NEAREST,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"35", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_LINEAR_MIPMAP_LINEAR,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"36", 	GL_REPEAT,			GL_CLAMP_TO_EDGE,	GL_LINEAR_MIPMAP_LINEAR,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"37", 	GL_REPEAT,			GL_REPEAT,			GL_NEAREST,					GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"38", 	GL_REPEAT,			GL_REPEAT,			GL_NEAREST,					GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"39", 	GL_REPEAT,			GL_REPEAT,			GL_LINEAR,					GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"40", 	GL_REPEAT,			GL_REPEAT,			GL_LINEAR,					GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"41", 	GL_REPEAT,			GL_REPEAT,			GL_NEAREST_MIPMAP_NEAREST,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"42", 	GL_REPEAT,			GL_REPEAT,			GL_NEAREST_MIPMAP_NEAREST,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"43", 	GL_REPEAT,			GL_REPEAT,			GL_NEAREST_MIPMAP_LINEAR,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"44", 	GL_REPEAT,			GL_REPEAT,			GL_NEAREST_MIPMAP_LINEAR,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"45", 	GL_REPEAT,			GL_REPEAT,			GL_LINEAR_MIPMAP_NEAREST,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"46", 	GL_REPEAT,			GL_REPEAT,			GL_LINEAR_MIPMAP_NEAREST,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
	{"47", 	GL_REPEAT,			GL_REPEAT,			GL_LINEAR_MIPMAP_LINEAR,	GL_NEAREST, 	9, {TEXTURE(mytexture_256_256)}},
	{"48", 	GL_REPEAT,			GL_REPEAT,			GL_LINEAR_MIPMAP_LINEAR,	GL_LINEAR, 		9, {TEXTURE(mytexture_256_256)}},
};


































































































