#ifndef __NMGLDEF_H__
#define __NMGLDEF_H__

#define NMGL_VERSION_ES_CL_1_0              1
#define NMGL_VERSION_ES_CM_1_1              1
#define NMGL_VERSION_ES_CL_1_1              1
#define NMGL_DEPTH_BUFFER_BIT               0x00000100
#define NMGL_STENCIL_BUFFER_BIT             0x00000400
#define NMGL_COLOR_BUFFER_BIT               0x00004000
#define NMGL_FALSE                          0
#define NMGL_TRUE                           1
#define NMGL_POINTS                         0x0000
#define NMGL_LINES                          0x0001
#define NMGL_LINE_LOOP                      0x0002
#define NMGL_LINE_STRIP                     0x0003
#define NMGL_TRIANGLES                      0x0004
#define NMGL_TRIANGLE_STRIP                 0x0005
#define NMGL_TRIANGLE_FAN                   0x0006
#define NMGL_NEVER                          0x0200
#define NMGL_LESS                           0x0201
#define NMGL_EQUAL                          0x0202
#define NMGL_LEQUAL                         0x0203
#define NMGL_GREATER                        0x0204
#define NMGL_NOTEQUAL                       0x0205
#define NMGL_GEQUAL                         0x0206
#define NMGL_ALWAYS                         0x0207
#define NMGL_ZERO                           0
#define NMGL_ONE                            1
#define NMGL_SRC_COLOR                      0x0300
#define NMGL_ONE_MINUS_SRC_COLOR            0x0301
#define NMGL_SRC_ALPHA                      0x0302
#define NMGL_ONE_MINUS_SRC_ALPHA            0x0303
#define NMGL_DST_ALPHA                      0x0304
#define NMGL_ONE_MINUS_DST_ALPHA            0x0305
#define NMGL_DST_COLOR                      0x0306
#define NMGL_ONE_MINUS_DST_COLOR            0x0307
#define NMGL_SRC_ALPHA_SATURATE             0x0308
#define NMGL_CLIP_PLANE0                    0x3000
#define NMGL_CLIP_PLANE1                    0x3001
#define NMGL_CLIP_PLANE2                    0x3002
#define NMGL_CLIP_PLANE3                    0x3003
#define NMGL_CLIP_PLANE4                    0x3004
#define NMGL_CLIP_PLANE5                    0x3005
#define NMGL_FRONT                          0x0404
#define NMGL_BACK                           0x0405
#define NMGL_FRONT_AND_BACK                 0x0408
#define NMGL_FOG                            0x0B60
#define NMGL_LIGHTING                       0x0B50
#define NMGL_TEXTURE_2D                     0x0DE1
#define NMGL_CULL_FACE                      0x0B44
#define NMGL_ALPHA_TEST                     0x0BC0
#define NMGL_BLEND                          0x0BE2
#define NMGL_COLOR_LOGIC_OP                 0x0BF2
#define NMGL_DITHER                         0x0BD0
#define NMGL_STENCIL_TEST                   0x0B90
#define NMGL_DEPTH_TEST                     0x0B71
#define NMGL_POINT_SMOOTH                   0x0B10
#define NMGL_LINE_SMOOTH                    0x0B20
#define NMGL_SCISSOR_TEST                   0x0C11
#define NMGL_COLOR_MATERIAL                 0x0B57
#define NMGL_NORMALIZE                      0x0BA1
#define NMGL_RESCALE_NORMAL                 0x803A
#define NMGL_VERTEX_ARRAY                   0x8074
#define NMGL_NORMAL_ARRAY                   0x8075
#define NMGL_COLOR_ARRAY                    0x8076
#define NMGL_TEXTURE_COORD_ARRAY            0x8078
#define NMGL_MULTISAMPLE                    0x809D
#define NMGL_SAMPLE_ALPHA_TO_COVERAGE       0x809E
#define NMGL_SAMPLE_ALPHA_TO_ONE            0x809F
#define NMGL_SAMPLE_COVERAGE                0x80A0
#define NMGL_NO_ERROR                       0
#define NMGL_INVALID_ENUM                   0x0500
#define NMGL_INVALID_VALUE                  0x0501
#define NMGL_INVALID_OPERATION              0x0502
#define NMGL_STACK_OVERFLOW                 0x0503
#define NMGL_STACK_UNDERFLOW                0x0504
#define NMGL_OUT_OF_MEMORY                  0x0505
#define NMGL_EXP                            0x0800
#define NMGL_EXP2                           0x0801
#define NMGL_FOG_DENSITY                    0x0B62
#define NMGL_FOG_START                      0x0B63
#define NMGL_FOG_END                        0x0B64
#define NMGL_FOG_MODE                       0x0B65
#define NMGL_FOG_COLOR                      0x0B66
#define NMGL_CW                             0x0900
#define NMGL_CCW                            0x0901
#define NMGL_CURRENT_COLOR                  0x0B00
#define NMGL_CURRENT_NORMAL                 0x0B02
#define NMGL_CURRENT_TEXTURE_COORDS         0x0B03
#define NMGL_POINT_SIZE                     0x0B11
#define NMGL_POINT_SIZE_MIN                 0x8126
#define NMGL_POINT_SIZE_MAX                 0x8127
#define NMGL_POINT_FADE_THRESHOLD_SIZE      0x8128
#define NMGL_POINT_DISTANCE_ATTENUATION     0x8129
#define NMGL_SMOOTH_POINT_SIZE_RANGE        0x0B12
#define NMGL_LINE_WIDTH                     0x0B21
#define NMGL_SMOOTH_LINE_WIDTH_RANGE        0x0B22
#define NMGL_ALIASED_POINT_SIZE_RANGE       0x846D
#define NMGL_ALIASED_LINE_WIDTH_RANGE       0x846E
#define NMGL_CULL_FACE_MODE                 0x0B45
#define NMGL_FRONT_FACE                     0x0B46
#define NMGL_SHADE_MODEL                    0x0B54
#define NMGL_DEPTH_RANGE                    0x0B70
#define NMGL_DEPTH_WRITEMASK                0x0B72
#define NMGL_DEPTH_CLEAR_VALUE              0x0B73
#define NMGL_DEPTH_FUNC                     0x0B74
#define NMGL_STENCIL_CLEAR_VALUE            0x0B91
#define NMGL_STENCIL_FUNC                   0x0B92
#define NMGL_STENCIL_VALUE_MASK             0x0B93
#define NMGL_STENCIL_FAIL                   0x0B94
#define NMGL_STENCIL_PASS_DEPTH_FAIL        0x0B95
#define NMGL_STENCIL_PASS_DEPTH_PASS        0x0B96
#define NMGL_STENCIL_REF                    0x0B97
#define NMGL_STENCIL_WRITEMASK              0x0B98
#define NMGL_MATRIX_MODE                    0x0BA0
#define NMGL_VIEWPORT                       0x0BA2
#define NMGL_MODELVIEW_STACK_DEPTH          0x0BA3
#define NMGL_PROJECTION_STACK_DEPTH         0x0BA4
#define NMGL_TEXTURE_STACK_DEPTH            0x0BA5
#define NMGL_MODELVIEW_MATRIX               0x0BA6
#define NMGL_PROJECTION_MATRIX              0x0BA7
#define NMGL_TEXTURE_MATRIX                 0x0BA8
#define NMGL_ALPHA_TEST_FUNC                0x0BC1
#define NMGL_ALPHA_TEST_REF                 0x0BC2
#define NMGL_BLEND_DST                      0x0BE0
#define NMGL_BLEND_SRC                      0x0BE1
#define NMGL_LOGIC_OP_MODE                  0x0BF0
#define NMGL_SCISSOR_BOX                    0x0C10
#define NMGL_COLOR_CLEAR_VALUE              0x0C22
#define NMGL_COLOR_WRITEMASK                0x0C23
#define NMGL_MAX_LIGHTS                     0x0D31
#define NMGL_MAX_CLIP_PLANES                0x0D32
#define NMGL_MAX_TEXTURE_SIZE               0x0D33
#define NMGL_MAX_MODELVIEW_STACK_DEPTH      0x0D36
#define NMGL_MAX_PROJECTION_STACK_DEPTH     0x0D38
#define NMGL_MAX_TEXTURE_STACK_DEPTH        0x0D39
#define NMGL_MAX_VIEWPORT_DIMS              0x0D3A
#define NMGL_MAX_TEXTURE_UNITS              0x84E2
#define NMGL_SUBPIXEL_BITS                  0x0D50
#define NMGL_RED_BITS                       0x0D52
#define NMGL_GREEN_BITS                     0x0D53
#define NMGL_BLUE_BITS                      0x0D54
#define NMGL_ALPHA_BITS                     0x0D55
#define NMGL_DEPTH_BITS                     0x0D56
#define NMGL_STENCIL_BITS                   0x0D57
#define NMGL_POLYGON_OFFSET_UNITS           0x2A00
#define NMGL_POLYGON_OFFSET_FILL            0x8037
#define NMGL_POLYGON_OFFSET_FACTOR          0x8038
#define NMGL_TEXTURE_BINDING_2D             0x8069
#define NMGL_VERTEX_ARRAY_SIZE              0x807A
#define NMGL_VERTEX_ARRAY_TYPE              0x807B
#define NMGL_VERTEX_ARRAY_STRIDE            0x807C
#define NMGL_NORMAL_ARRAY_TYPE              0x807E
#define NMGL_NORMAL_ARRAY_STRIDE            0x807F
#define NMGL_COLOR_ARRAY_SIZE               0x8081
#define NMGL_COLOR_ARRAY_TYPE               0x8082
#define NMGL_COLOR_ARRAY_STRIDE             0x8083
#define NMGL_TEXTURE_COORD_ARRAY_SIZE       0x8088
#define NMGL_TEXTURE_COORD_ARRAY_TYPE       0x8089
#define NMGL_TEXTURE_COORD_ARRAY_STRIDE     0x808A
#define NMGL_VERTEX_ARRAY_POINTER           0x808E
#define NMGL_NORMAL_ARRAY_POINTER           0x808F
#define NMGL_COLOR_ARRAY_POINTER            0x8090
#define NMGL_TEXTURE_COORD_ARRAY_POINTER    0x8092
#define NMGL_SAMPLE_BUFFERS                 0x80A8
#define NMGL_SAMPLES                        0x80A9
#define NMGL_SAMPLE_COVERAGE_VALUE          0x80AA
#define NMGL_SAMPLE_COVERAGE_INVERT         0x80AB
#define NMGL_NUM_COMPRESSED_TEXTURE_FORMATS 0x86A2
#define NMGL_COMPRESSED_TEXTURE_FORMATS     0x86A3
#define NMGL_DONT_CARE                      0x1100
#define NMGL_FASTEST                        0x1101
#define NMGL_NICEST                         0x1102
#define NMGL_PERSPECTIVE_CORRECTION_HINT    0x0C50
#define NMGL_POINT_SMOOTH_HINT              0x0C51
#define NMGL_LINE_SMOOTH_HINT               0x0C52
#define NMGL_FOG_HINT                       0x0C54
#define NMGL_GENERATE_MIPMAP_HINT           0x8192
#define NMGL_LIGHT_MODEL_AMBIENT            0x0B53
#define NMGL_LIGHT_MODEL_TWO_SIDE           0x0B52
#define NMGL_AMBIENT                        0x1200
#define NMGL_DIFFUSE                        0x1201
#define NMGL_SPECULAR                       0x1202
#define NMGL_POSITION                       0x1203
#define NMGL_SPOT_DIRECTION                 0x1204
#define NMGL_SPOT_EXPONENT                  0x1205
#define NMGL_SPOT_CUTOFF                    0x1206
#define NMGL_CONSTANT_ATTENUATION           0x1207
#define NMGL_LINEAR_ATTENUATION             0x1208
#define NMGL_QUADRATIC_ATTENUATION          0x1209
#define NMGL_BYTE                           0x1400
#define NMGL_UNSIGNED_BYTE                  0x1401
#define NMGL_SHORT                          0x1402
#define NMGL_UNSIGNED_SHORT                 0x1403
#define NMGL_FLOAT                          0x1406
#define NMGL_FIXED                          0x140C
#define NMGL_CLEAR                          0x1500
#define NMGL_AND                            0x1501
#define NMGL_AND_REVERSE                    0x1502
#define NMGL_COPY                           0x1503
#define NMGL_AND_INVERTED                   0x1504
#define NMGL_NOOP                           0x1505
#define NMGL_XOR                            0x1506
#define NMGL_OR                             0x1507
#define NMGL_NOR                            0x1508
#define NMGL_EQUIV                          0x1509
#define NMGL_INVERT                         0x150A
#define NMGL_OR_REVERSE                     0x150B
#define NMGL_COPY_INVERTED                  0x150C
#define NMGL_OR_INVERTED                    0x150D
#define NMGL_NAND                           0x150E
#define NMGL_SET                            0x150F
#define NMGL_EMISSION                       0x1600
#define NMGL_SHININESS                      0x1601
#define NMGL_AMBIENT_AND_DIFFUSE            0x1602
#define NMGL_MODELVIEW                      0x1700
#define NMGL_PROJECTION                     0x1701
#define NMGL_TEXTURE                        0x1702
#define NMGL_ALPHA                          0x1906
#define NMGL_RGB                            0x1907
#define NMGL_RGBA                           0x1908
#define NMGL_LUMINANCE                      0x1909
#define NMGL_LUMINANCE_ALPHA                0x190A
#define NMGL_UNPACK_ALIGNMENT               0x0CF5
#define NMGL_PACK_ALIGNMENT                 0x0D05
#define NMGL_UNSIGNED_SHORT_4_4_4_4         0x8033
#define NMGL_UNSIGNED_SHORT_5_5_5_1         0x8034
#define NMGL_UNSIGNED_SHORT_5_6_5           0x8363
#define NMGL_FLAT                           0x1D00
#define NMGL_SMOOTH                         0x1D01
#define NMGL_KEEP                           0x1E00
#define NMGL_REPLACE                        0x1E01
#define NMGL_INCR                           0x1E02
#define NMGL_DECR                           0x1E03
#define NMGL_VENDOR                         0x1F00
#define NMGL_RENDERER                       0x1F01
#define NMGL_VERSION                        0x1F02
#define NMGL_EXTENSIONS                     0x1F03
#define NMGL_MODULATE                       0x2100
#define NMGL_DECAL                          0x2101
#define NMGL_ADD                            0x0104
#define NMGL_TEXTURE_ENV_MODE               0x2200
#define NMGL_TEXTURE_ENV_COLOR              0x2201
#define NMGL_TEXTURE_ENV                    0x2300
#define NMGL_NEAREST                        0x2600
#define NMGL_LINEAR                         0x2601
#define NMGL_NEAREST_MIPMAP_NEAREST         0x2700
#define NMGL_LINEAR_MIPMAP_NEAREST          0x2701
#define NMGL_NEAREST_MIPMAP_LINEAR          0x2702
#define NMGL_LINEAR_MIPMAP_LINEAR           0x2703
#define NMGL_TEXTURE_MAG_FILTER             0x2800
#define NMGL_TEXTURE_MIN_FILTER             0x2801
#define NMGL_TEXTURE_WRAP_S                 0x2802
#define NMGL_TEXTURE_WRAP_T                 0x2803
#define NMGL_GENERATE_MIPMAP                0x8191
#define NMGL_TEXTURE0                       0x84C0
#define NMGL_TEXTURE1                       0x84C1
#define NMGL_TEXTURE2                       0x84C2
#define NMGL_TEXTURE3                       0x84C3
#define NMGL_TEXTURE4                       0x84C4
#define NMGL_TEXTURE5                       0x84C5
#define NMGL_TEXTURE6                       0x84C6
#define NMGL_TEXTURE7                       0x84C7
#define NMGL_TEXTURE8                       0x84C8
#define NMGL_TEXTURE9                       0x84C9
#define NMGL_TEXTURE10                      0x84CA
#define NMGL_TEXTURE11                      0x84CB
#define NMGL_TEXTURE12                      0x84CC
#define NMGL_TEXTURE13                      0x84CD
#define NMGL_TEXTURE14                      0x84CE
#define NMGL_TEXTURE15                      0x84CF
#define NMGL_TEXTURE16                      0x84D0
#define NMGL_TEXTURE17                      0x84D1
#define NMGL_TEXTURE18                      0x84D2
#define NMGL_TEXTURE19                      0x84D3
#define NMGL_TEXTURE20                      0x84D4
#define NMGL_TEXTURE21                      0x84D5
#define NMGL_TEXTURE22                      0x84D6
#define NMGL_TEXTURE23                      0x84D7
#define NMGL_TEXTURE24                      0x84D8
#define NMGL_TEXTURE25                      0x84D9
#define NMGL_TEXTURE26                      0x84DA
#define NMGL_TEXTURE27                      0x84DB
#define NMGL_TEXTURE28                      0x84DC
#define NMGL_TEXTURE29                      0x84DD
#define NMGL_TEXTURE30                      0x84DE
#define NMGL_TEXTURE31                      0x84DF
#define NMGL_ACTIVE_TEXTURE                 0x84E0
#define NMGL_CLIENT_ACTIVE_TEXTURE          0x84E1
#define NMGL_REPEAT                         0x2901
#define NMGL_CLAMP_TO_EDGE                  0x812F
#define NMGL_LIGHT0                         0x4000
#define NMGL_LIGHT1                         0x4001
#define NMGL_LIGHT2                         0x4002
#define NMGL_LIGHT3                         0x4003
#define NMGL_LIGHT4                         0x4004
#define NMGL_LIGHT5                         0x4005
#define NMGL_LIGHT6                         0x4006
#define NMGL_LIGHT7                         0x4007
#define NMGL_ARRAY_BUFFER                   0x8892
#define NMGL_ELEMENT_ARRAY_BUFFER           0x8893
#define NMGL_ARRAY_BUFFER_BINDING           0x8894
#define NMGL_ELEMENT_ARRAY_BUFFER_BINDING   0x8895
#define NMGL_VERTEX_ARRAY_BUFFER_BINDING    0x8896
#define NMGL_NORMAL_ARRAY_BUFFER_BINDING    0x8897
#define NMGL_COLOR_ARRAY_BUFFER_BINDING     0x8898
#define NMGL_TEXTURE_COORD_ARRAY_BUFFER_BINDING 0x889A
#define NMGL_STATIC_DRAW                    0x88E4
#define NMGL_DYNAMIC_DRAW                   0x88E8
#define NMGL_BUFFER_SIZE                    0x8764
#define NMGL_BUFFER_USAGE                   0x8765
#define NMGL_SUBTRACT                       0x84E7
#define NMGL_COMBINE                        0x8570
#define NMGL_COMBINE_RGB                    0x8571
#define NMGL_COMBINE_ALPHA                  0x8572
#define NMGL_RGB_SCALE                      0x8573
#define NMGL_ADD_SIGNED                     0x8574
#define NMGL_INTERPOLATE                    0x8575
#define NMGL_CONSTANT                       0x8576
#define NMGL_PRIMARY_COLOR                  0x8577
#define NMGL_PREVIOUS                       0x8578
#define NMGL_OPERAND0_RGB                   0x8590
#define NMGL_OPERAND1_RGB                   0x8591
#define NMGL_OPERAND2_RGB                   0x8592
#define NMGL_OPERAND0_ALPHA                 0x8598
#define NMGL_OPERAND1_ALPHA                 0x8599
#define NMGL_OPERAND2_ALPHA                 0x859A
#define NMGL_ALPHA_SCALE                    0x0D1C
#define NMGL_SRC0_RGB                       0x8580
#define NMGL_SRC1_RGB                       0x8581
#define NMGL_SRC2_RGB                       0x8582
#define NMGL_SRC0_ALPHA                     0x8588
#define NMGL_SRC1_ALPHA                     0x8589
#define NMGL_SRC2_ALPHA                     0x858A
#define NMGL_DOT3_RGB                       0x86AE
#define NMGL_DOT3_RGBA                      0x86AF

//custom
//------------------------CUSTOMIZE-THIS-ONLY-----------------------------------------------------------------
#define NMGL_MAX_MIPMAP_LVL                 10  //square textures only; 1024 width/height
#define BYTES_IN_CHAR                       4
//------------------------------------------------------------------------------------------------------------
#define RGBA_TEXEL_SIZE_UBYTE              4
#define RGB_TEXEL_SIZE_UBYTE               3
#define LUMINANCE_ALPHA_TEXEL_SIZE_UBYTE   2
#define LUMINANCE_TEXEL_SIZE_UBYTE         1
#define ALPHA_TEXEL_SIZE_UBYTE             1

#define NMGL_MAX_TEX_SIDE (0x1<<(NMGL_MAX_MIPMAP_LVL))
#define UBYTES_PER_TEXEL RGBA_TEXEL_SIZE_UBYTE   //each byte of texel is placed in 4-byte var (because char is 4-byte variable)
#define MIPMAP_OBJ_SIZE ((((0x1<<(2*(NMGL_MAX_MIPMAP_LVL+1)))-1)/3)*UBYTES_PER_TEXEL) //mipmap mem size in 4byte words	
#define MIPMAP_MEM_SIZE ((MIPMAP_OBJ_SIZE)*NMGL_MAX_TEX_OBJECTS) //mipmap mem size in NMGLubyte	

#ifdef DEBUG 
#define DEBUG_PRINT(x) printf x  
#else 
#define DEBUG_PRINT(x) do {} while (0)
#endif

#endif
